version: '3.8'

services:
  #frontend:
  #    build:
  #      context: .
  #      dockerfile: ./docker/nginx/Dockerfile
  #    volumes:
  #      - ./index.html:/usr/share/nginx/html/index.html
  #      - ./vendor:/usr/share/nginx/html/vendor
  #      - ./frontend:/usr/share/nginx/html/frontend
  #      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #    ports:
  #      - "8080:80"
  #    depends_on:
  #      - php
        
  php:
    build:
      context: .
      dockerfile: ./docker/php-api/Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "8081:80" 
    depends_on:
      - db

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8082:8080"
    environment:
      - SWAGGER_JSON=/swagger/openapi.yaml
    volumes:
      - ./docs/swagger:/swagger

  mqtt-subscriber:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - "8083:80"
    container_name: mqtt-subscriber
    depends_on:
      - db
    restart: always

  mysql-cron-backup:
    image: fradelg/mysql-cron-backup
    depends_on:
      - db
    volumes:
      - ./backup:/backup
    environment:
      - MYSQL_HOST=mysql_main
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MAX_BACKUPS=15
      - INIT_BACKUP=0
      # Every day at 03:00
      - CRON_TIME=0 3 * * *
      # Make it small
      - GZIP_LEVEL=9
    restart: unless-stopped
  db:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=your-org
      - DOCKER_INFLUXDB_INIT_BUCKET=weather
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=your-token

volumes:
    influxdb-data:
