version: '3.8'

services:
  frontend:
    
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./vendor:/usr/share/nginx/html/vendor
      - ./frontend:/usr/share/nginx/html/frontend
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./docker/php-api/Dockerfile
    volumes:
      - ./docker/php-api:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weather
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  db-data:
